# Generated by Django 4.2.27 on 2025-12-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaster',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='reportscategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
