# Generated by Django 4.2.27 on 2025-12-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0003_alter_reportmaster_file_alter_reportscategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportscategory',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
