# Generated by Django 5.2.9 on 2025-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0004_reportscategory_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
