# Generated by Django 4.2.27 on 2025-12-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0005_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
