# Generated by Django 5.2.9 on 2025-12-09 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0005_cart_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_report', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('is_viewed_ads', models.BooleanField(blank=True, default=False, null=True)),
                ('no_of_ads', models.IntegerField(blank=True, default=0, null=True)),
                ('ad_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('report_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_cat', to='apis_v1.reportscategory')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_master', to='apis_v1.reportmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
