# Generated by Django 4.2.27 on 2025-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0006_usermaster_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
    ]
