# Generated by Django 4.2.27 on 2025-12-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0007_cart_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=True)),
                ('unlocked_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('unlocked_on', models.DateTimeField(blank=True, null=True)),
                ('ads_count', models.IntegerField(default=0)),
                ('ads_duration', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports_id', to='apis_v1.reportmaster')),
                ('report_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports_category_id', to='apis_v1.reportscategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
