# Generated by Django 4.2.27 on 2025-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0008_usergeneratedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usergeneratedreport',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergeneratedreport',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
